### ISSUE TITLE
Docker and Docker-compose files incorrect + java.net.ConnectException

### ISSUE THREAD

**Issue by steppo83** [kermitt2/biblio-glutton#79]
Hello,
Some points to help users that will user biblio-glutton in Windows env with Docker.

- You need to clone the repo using this args **--config core.autocrlf=input** so the command will be git clone https://github.com/kermitt2/biblio-glutton.git --config core.autocrlf=input otherwise you'll have strange errors during docker-compose up phase
- Docker file is not right, it needs the last command to be CMD java -jar lib/lookup-service-0.2-onejar.jar server /app/config/glutton.yml
- Docker compose file is not right, needs to have volume for config otherwise the jar file says that it cannot find it, so

volumes:
      - .\data:/app/data
      - .\config:/app/config

Even with all those changes, the service starts but biblio-glutton has java.net.ConnectException of Connection refused.

WARN  [2022-09-26 07:48:02,191] org.eclipse.jetty.server.HttpChannel: handleException /service/data java.net.ConnectException: Connection refused
WARN  [2022-09-26 07:48:02,192] org.eclipse.jetty.server.HttpChannelState: unhandled due to prior sendError

Do I have to to a pull request for the changes above?
Can you help me about the error of connection refused?

Thanks

**Comment by steppo83** [comment]
I found why: inside the glutton.yml config file, there was written 
elastic:
  host: localhost:9200 -> THIS IS WRONG, has to be **elasticsearch:9200**
  index: crossrefdata
  maxConnections: 20

**Comment by lfoppiano** [comment]
Dear @steppo83, thanks for the interest in biblio-glutton. 
I've created a PR some time ago to address some of the problems (e.g. configuration) you're facing, please check it out: #73 

In addition I should have improved the documentation, please check the branch's documentation here: https://github.com/kermitt2/biblio-glutton/tree/feature/docker#running-with-docker 

Regarding the information about windows, we can add them in the user guide which is, at the moment, in the README.MD file. At the moment you could branch out from `feature/docker`, add the information related to windows, and open a PR to that branch instead of master.

**Comment by steppo83** [comment]
Dear @lfoppiano, thanks a lot for your answer.
I created a PR starting from  feature/docker branch.

Thanks!
