### ISSUE TITLE
What's the best way to understand the logic used for consolidation?

### ISSUE THREAD

**Issue by davidefiocco** [kermitt2/biblio-glutton#89]
Hello! I have started to review the logic used for consolidation, and it should boil down to analyzing

https://github.com/kermitt2/grobid/tree/master/grobid-core/src/main/java/org/grobid/core/engines/CitationParser.java
https://github.com/kermitt2/grobid/tree/master/grobid-core/src/main/java/org/grobid/core/utilities/Consolidation.java
https://github.com/kermitt2/grobid/tree/master/grobid-core/src/main/java/org/grobid/core/utilities/glutton/GluttonRequest.java

but is there more I should have a look at? Is there a documentation that describes the consolidation logic used in `biblio-glutton`?

Thanks a lot!

**Comment by lfoppiano** [comment]
It's a bit embarassing for the delay, but to manage all these projects is necessary a battery of developers. Instead it's only one or two people. 

Indeed, that's the logic for the grobid consolidation. I think the best documentation is the code 😄 

I close it, since I guess is not needed anymore, in case feel free to reopen it.

**Comment by davidefiocco** [comment]
Thanks @lfoppiano, I appreciate the reply, no worries about the delay!

**Comment by lfoppiano** [comment]
[Here](https://github.com/kermitt2/grobid/issues/1140#issue-2394951264) some additional information.
